spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: localmysql

mybatis-plus:
  type-enums-package: com.zpycloud.**.enums # mybatisplus????3.5????????entity??????????
